name = "Sean Testing"
author = "XeratulXE"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57174c4f363c651754e816371e3a0084c516f97e498b8744a157efdf537b6065"

[versions]
minecraft = "1.21.9"
quilt = "0.27.1"
